version: 0.1
phases:
  install:
    commands:
      - wget http://security.ubuntu.com/ubuntu/pool/main/a/apt/apt_1.0.1ubuntu2.17_amd64.deb -O apt.deb
      - sudo dpkg -i apt.deb
      - apt-get update && apt-get install python-pip
      - pip install awscli
      - npm install
  build:
    commands:
      - npm run build
      - cd dist
      - aws s3 cp dist/ s3://demo-pipeline-1/
artifacts:
  type: zip
  files: dist/*
