version: 0.1
phases:
  install:
    commands:
      - apt-get update && apt-get install python-pip
      - pip install awscli
      - npm install
  build:
    commands:
      - npm run build
      - cd dist
      - aws s3 cp dist/ s3://demo-pipeline-1/
artifacts:
  type: zip
  files: dist/*
